replicaCount: 1

image:
  repository: todo-list-fe
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 32080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
